foreground         #F4F3F6
background         #1B1B1D
cursor             #ff9050

selection_foreground #202020
selection_background #ff9050

active_tab_foreground     #1B1B1D
active_tab_background     #F4F3F6
inactive_tab_foreground   #F4F3F6
inactive_tab_background   #1B1B1D

active_border_color   #F4F3F6
inactive_border_color #1B1B1D
bell_border_color     #808488

color0      #464649
color1		#808488
color2		#B8737A
color3		#8C8482
color4		#9A7D82
color5		#A5A499
color6		#A7A6AC
color7		#E7E6EA
color8		#A1A1A4
color9		#848A91
color10		#E06F7A
color11		#AA9F9C
color12		#CEA7AD
color13		#DCDACC
color14		#DFDDE6
color15		#E7E6EA
