$background = rgb(1B1B1D)
$backgroundColTransparent = rgba(1B1B1D80)
$foreground = rgb(F4F3F6)
$color0 = rgb(464649)
$color1 = rgb(808488)
$color2 = rgb(B8737A)
$color2_shadow = rgba(B8737Aa0)
$color3 = rgb(8C8482)
$color4 = rgb(9A7D82)
$color5 = rgb(A5A499)
$color6 = rgb(A7A6AC)
$color7 = rgb(E7E6EA)
$color8 = rgb(A1A1A4)
$color9 = rgb(848A91)
$color10 = rgb(E06F7A)
$color11 = rgb(AA9F9C)
$color12 = rgb(CEA7AD)
$color13 = rgb(DCDACC)
$color14 = rgb(DFDDE6)
$color15 = rgb(E7E6EA)
