# wallust 3.0 beta.*

backend = "fastresize"
# color_space = "lch"
palette = "dark16"

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
threshold = 8
check_contrast = true

[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

eww.template = 'colors-eww.scss'
eww.target = '~/.config/eww/wallust/colors-eww.scss'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/theme.conf'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/wallust/colors-wallust.css'

wlogout.template = 'colors-swaync.css'
wlogout.target = '~/.config/wlogout/wallust/colors-wallust.css'

ghostty.template = 'colors-ghostty'
ghostty.target = '~/.config/ghostty/themes/wallust'

#macchina.template = 'colors-macchina.toml'
#macchina.target = '~/.config/macchina/themes/wallust.toml'

#wezterm.template = 'colors-wezterm.toml'
#wezterm.target = '~/.config/wezterm/colors/wallust.toml'

#zathura.template = 'colors-zathura'
#zathura.target = '~/.config/zathura/zathurarc'
